config:
  goShortsJson: '{}'
goLinkShortener:
  goLinkShortener:
    image:
      repository: ghcr.io/tim-krehan/go-link-shortener
      tag: v1.1.2
  replicas: 1
kubernetesClusterDomain: cluster.local
service:
  ports:
  - port: 8081
    protocol: TCP
    targetPort: 8081
  type: ClusterIP
