apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "chart.fullname" . }}-config
  labels:
  {{- include "chart.labels" . | nindent 4 }}
data:
  go-shorts.json: |
    {"shorts":{{ toJson .Values.config }}}
