apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "chart.fullname" . }}-go-link-shortener
  labels:
    app: go-link-shortener
  {{- include "chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.goLinkShortener.replicas }}
  selector:
    matchLabels:
      app: go-link-shortener
    {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: go-link-shortener
      {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: KUBERNETES_CLUSTER_DOMAIN
          value: {{ quote .Values.kubernetesClusterDomain }}
        image: {{ .Values.goLinkShortener.goLinkShortener.image.repository }}:{{ .Values.goLinkShortener.goLinkShortener.image.tag
          | default .Chart.AppVersion }}
        name: go-link-shortener
        ports:
        - containerPort: 8081
        resources: {}
        volumeMounts:
        - mountPath: /app/go-shorts.json
          name: config-volume
          subPath: go-shorts.json
      volumes:
      - configMap:
          name: {{ include "chart.fullname" . }}-config
        name: config-volume
