apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "chart.fullname" . }}-ingress
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  rules:
  - host: go-link-shortener.local
    http:
      paths:
      - backend:
          service:
            name: '{{ include "chart.fullname" . }}-service'
            port:
              number: 8081
        path: /
        pathType: Prefix
